name: build-image
on:
  workflow_dispatch:

env:
  FLATCAR_VERSION: 3760.2.0
  FLATCAR_CHANNEL: stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: kubernetes-sigs/image-builder
      #- uses: actions/cache@v4
      #  with:
      #    path: ${{ github.workspace }}/output
      #    key: .cache
      - name: build-image
        run: |
          sudo chmod 666 /dev/kvm
          docker build -t image-builder images/capi
          mkdir ${{ github.workspace }}/output && chmod 777 ${{ github.workspace }}/output
          mkdir ${{ github.workspace }}/.cache && chmod 777 ${{ github.workspace }}/.cache
          docker run --rm --privileged -e PACKER_FLAGS="--var 'kubernetes_semver=v1.28.4'" -e PACKER_LOG=1 -v ${{ github.workspace }}/output:/home/imagebuilder/output/ -v ${{ github.workspace }}/.cache:/home/imagebuilder/.cache/ -e FLATCAR_CHANNEL=$FLATCAR_CHANNEL -e FLATCAR_VERSION=$FLATCAR_VERSION -e OEM_ID=kubevirt image-builder build-qemu-flatcar
          ls -lha ${{ github.workspace }}/output
          ls -lha ${{ github.workspace }}/output/flatcar-stable-3760.2.0-kube-v1.28.4
          ls -lha ${{ github.workspace }}/.cache
      - uses: actions/upload-artifact@v4
        with:
          name: flatcar-$FLATCAR_CHANNEL-$FLATCAR_VERSION-kube-v1.28.6
          path: ${{ github.workspace }}/output/flatcar-$FLATCAR_CHANNEL-$FLATCAR_VERSION-kube-v1.28.6/flatcar-$FLATCAR_CHANNEL-$FLATCAR_VERSION-kube-v1.28.6
